#!/bin/sh
#
# php-fpm - this script starts and stops the php-fpm daemin
#
# chkconfig: - 85 15
# processname: php-fpm
# config:      /etc/php-fpm.conf

set -e

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DESC="php-fpm daemon"
NAME=php-fpm
DAEMON=/usr/sbin/$NAME
CONFIGFILE=/etc/php-fpm.conf
PHPINI=/etc/php.ini
PIDFILE=/opt/bin/var/run/$NAME.pid
SCRIPTNAME=/opt/bin/$NAME

# If the daemon file is not found, terminate the script.
test -x $DAEMON || exit 0

d_start() {
    $DAEMON -y $CONFIGFILE -c $PHPINI -g $PIDFILE || echo " already running"
}
d_stop(){
    kill -QUIT `cat $PIDFILE` || echo " no running"
}

d_reload(){
    kill -HUP `cat $PIDFILE` || echo " could not reload"
}

case "$1" in
    start)
        echo "Starting $DESC"
        d_start
	echo "$DESC: $NAME  has started."
        ;;
    stop)
        echo "Stopping $DESC: $NAME"
        d_stop
	echo "$DESC: $NAME  has stoped."
        ;;
    reload)
        echo "Reloading $DESC configuration..."
        d_reload
        echo "Reloaded."
        ;;
    restart)
        echo "Restarting $DESC: $NAME"
        d_stop
        # Sleep for two seconds before starting again, this should give the nginx daemon some time to perform a graceful stop
        sleep 2
        d_start
        echo "."
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|restart|force-reload)" >&2
        exit 3
        ;;
esac
exit 0
