@echo off

set PRE=nimitz
set CONF=conf
set LIB=lib
set TARGET=target
set SEMANTIC=%PRE%_semantic
set FLOW=flow
set session=session


set NIMITZ_PATH=C:\repository\git\otherproject\nimitz
set NIMITZ_PATH_DEST=C:\repository\git\otherproject\nimitzdest

set SMARTHOME=smarthome
set NIMITZ_SEMANTIC_PATH=%NIMITZ_PATH%\%SEMANTIC%
set NIMITZ_SEMANTIC_SMARTHOME=%SEMANTIC%_%SMARTHOME%
mkdir %NIMITZ_PATH_DEST%\%SEMANTIC%\%NIMITZ_SEMANTIC_SMARTHOME%
copy /Y  %NIMITZ_SEMANTIC_PATH%\%NIMITZ_SEMANTIC_SMARTHOME%\target\%NIMITZ_SEMANTIC_SMARTHOME%.jar  %NIMITZ_PATH_DEST%\%SEMANTIC%\%NIMITZ_SEMANTIC_SMARTHOME%
xcopy /Y  %NIMITZ_SEMANTIC_PATH%\%NIMITZ_SEMANTIC_SMARTHOME%\target\%LIB%  %NIMITZ_PATH_DEST%\%SEMANTIC%\%NIMITZ_SEMANTIC_SMARTHOME% /s /e
xcopy /Y  %NIMITZ_SEMANTIC_PATH%\%NIMITZ_SEMANTIC_SMARTHOME%\target\%CONF%  %NIMITZ_PATH_DEST%\%SEMANTIC%\%NIMITZ_SEMANTIC_SMARTHOME% /s /e
pause