@echo off

mkdir %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME%
mkdir %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME%\%LIB%
mkdir %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME%\%CONF%
copy  %NIMITZ_PROJECT_PATH%\%PROJECT_NAME%\target\%PROJECT_NAME%.jar  %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME% 
copy  %NIMITZ_PROJECT_PATH%\%PROJECT_NAME%\target\bin\startup.sh  %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME% 
copy  %NIMITZ_PROJECT_PATH%\%PROJECT_NAME%\target\bin\shutdown.sh  %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME% 
xcopy %NIMITZ_PROJECT_PATH%\%PROJECT_NAME%\target\%LIB%  %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME%\%LIB% /s /e /f /Y 
xcopy %NIMITZ_PROJECT_PATH%\%PROJECT_NAME%\target\%CONF%  %NIMITZ_PATH_DEST%\%PARENT_PROJECT%\%PROJECT_NAME%\%CONF% /s /e  /f /Y 